### ISSUE TITLE
Information of "saving" rates ?

### ISSUE THREAD

**Issue by behrica** [asreview/systematic-review-datasets#26]
Did you use in some form all these datasets for simulation studies ?
So, do you have some numbers "how much effort" can be saved potentially using ASReview for a larger number of reviews ?

**Comment by GerbrichFerdinands** [comment]
Hi @behrica, thanks for filing this issue! 

In the past few months I've performed several simulation studies on six different datasets, of which five are currently stored in this repository (the datasets on PTSD, AceInhibitors, Wilson disease, Software fault prediction, and Virus Metagenomics). In short, for all six datasets ASReview could have saved at least 60% of screening effort (e.g. WSS95% was < 40%). For some datasets, ASReview was even able to detect 95% of relevant publiations after screening only 5% of relevant publications. 

In response to this issue, I've [drafted this PR](https://github.com/asreview/asreview/pull/284) containing [a document](https://github.com/asreview/asreview/blob/48ae38fa092379554e308304dd79ab36bb4b47cd/docs/source/simulation_study_results.rst) with results of these simulation studies (both numbers and figures). If you're looking for a more detailed account, please refer to my [master's thesis](https://github.com/GerbrichFerdinands/asreview-thesis/blob/master/manuscript/manuscript/Ferdinands%2C-G---MSBBSS.pdf/).

**Comment by behrica** [comment]
I did one simulation of an SR we did, and it looks like this:

![image](https://user-images.githubusercontent.com/127361/85069318-3171e980-b1b4-11ea-8da0-9cb91ac3ff61.png)


So the WSS100% is 85% , so a rather small gain.

Specially, if we would then factor in that we do our manual screening in an "integrated" multiuser tool, while usage of any external software would require effort in input/output. 

But yes, WSS95% with 5 % screening is a strong argument....

**Comment by Rensvandeschoot** [comment]
Dear @behrica,

Thank you for testing the software with your data! This is highly appreciated!!

We have seen such performance before and it was either one of these two reasons causing the slow inclusion rate at the end:

1. Missing data: If abstracts are missing, especially for the included papers, the model has a hard time learning. This can happen for example if entries with missing abstracts are included after searching for more information outside the software (e.g., by searching the full text, reading it and then decide to include - the model does not have this information so it can never learn why this abstract has been included), or if ALL entries with missing abstracts are included (e.g., because you want to find the full text in the next stage - then inclusion is random).

2. Sub-questions: We have encountered examples where researchers were actually working on multiple sub-questions within a search. If you then start with 1 target paper from the cluster of papers belonging to one sub-question the model will first explore the parameter space for this cluster of papers, then it takes many random papers before finding the next cluster. 

So, my question to you:
Can you send us the DOI of the data so that we can add your data to [this ](https://github.com/asreview/systematic-review-datasets) repo. Then we can run some tests for you.


Thank you!

_Prof. Dr. Rens van de Schoot - Department of Methodology & Statistics – Faculty of Social and Behavioral Sciences - Utrecht University –  The Netherlands  - Member Young Academy of the Royal Dutch Academy of Science_

**Comment by Rensvandeschoot** [comment]
see also this blogpost:[ https://asreview.nl/the-importance-of-abstracts/]( https://asreview.nl/the-importance-of-abstracts/)

**Comment by behrica** [comment]
> We have seen such performance before and it was either one of these two reasons causing the slow inclusion rate at the end:
> 
> 1. Missing data: If abstracts are missing, especially for the included papers, the model has a hard time learning. This can happen for example if entries with missing abstracts are included after searching for more information outside the software (e.g., by searching the full text, reading it and then decide to include - the model does not have this information so it can never learn why this abstract has been included), or if ALL entries with missing abstracts are included (e.g., because you want to find the full text in the next stage - then inclusion is random).

I will check this. I have indeed seen some missing text in "abstracts" (while title present), but left it in.
I will retry and let you know.

> 2. Sub-questions: We have encountered examples where researchers were actually working on multiple sub-questions within a search. If you then start with 1 target paper from the cluster of papers belonging to one sub-question the model will first explore the parameter space for this cluster of papers, then it takes many random papers before finding the next cluster.
> 
I check with my colleges
> So, my question to you:
> Can you send us the DOI of the data so that we can add your data to [this ](https://github.com/asreview/systematic-review-datasets) repo. Then we can run some tests for you.
> 
I work for the European Food Safety Authority and
we have actually a database of maybe arround 100 systematic reviews.
We publish the results of SRs anyway for each of our scientific outputs,
so I think it should be possible to share this with you.

2 issues:
- sometimes (often ??) we don't have DOIs for the references, but only title, authors, journal, year
- we have the abstract texts (which you need in the end) in our database, but I am sure, those we cannot share at all for copyright reasons

If you are interested, we could maybe organize a online meeting to discuss the eventual sharing of our SR database with you.

My contact is:
Carsten Behring
Data scientist
carsten.behring@efsa.europa.eu

**Comment by GerbrichFerdinands** [comment]
Hi @behrica, 

Nice that you've performed a simulation on your own data. I agree with you that finding 100% of relevant papers only after screening 85% of the data is not very impressive. Very interesting result for me as I am currently looking into how dataset characteristics relate to model performance.

I know of two studies stating that performance is worse for smaller datasets and datasets with a relatively small inclusion rate (see [Rathbone (2015)](https://doi.org/10.1186/s13643-015-0067-6) and [Gates (2018)](https://systematicreviewsjournal.biomedcentral.com/articles/10.1186/s13643-018-0707-8). (Although on the latter, my simulations demonstrated the opposite: performance was higher for datasets with the lowest inclusion rates.)

Therefore, besides the two points @Rensvandeschoot mentioned, I would be interested in the following statistics on your data: how many papers are in your search, how many of them are relevant, are there records with missing abstracts in your data? 


In the table below you can find the WSS@100 values from my simulations (for the default model). 

|dataset  |model       | wss.100|
|:--------|:-----------|-------:|
|ace      |NB + TF-IDF |   47.65|
|nudging  |NB + TF-IDF |   44.17|
|ptsd     |NB + TF-IDF |   89.34|
|software |NB + TF-IDF |   83.15|
|virus    |NB + TF-IDF |   54.08|
|wilson   |NB + TF-IDF |   86.31|

I opted for presenting WSS95% instead of 100%, because I think that we can never be sure of finding 100% of relevant publications unless we screen the whole dataset. And even then we might miss relevant papers, as the review process is prone to human error ([Wang, 2020](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0227742)).  As you say, we can only "try to make this sure" to find all relevant publications. But this is of course an ongoing discussion that varies widely across research areas, and I think that the cut-off value for the WSS should depend on the opinion researcher who is conducting the review.
 
Your work at the European Food Safety Authority sounds very interesting, we are eager to meet! I will send you an email.
